spring:
  application:
    name: eureka-server
server:
  port: 8761
  address: platform-eureka

eureka:
  instance:
    hostname: platform-eureka
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka